# Generated by Django 4.1.6 on 2023-03-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='astro_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astro_name', models.CharField(max_length=200)),
                ('astrophone_no', models.IntegerField()),
                ('astroEmail', models.EmailField(max_length=254)),
                ('astrolocation', models.CharField(max_length=5000)),
                ('astropassword', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='astro_pooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pooja_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Articals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articledate', models.DateField()),
                ('articletitle', models.CharField(max_length=50000)),
                ('articledescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='monthmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=200)),
                ('sign_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='panchag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=200)),
                ('Country_id', models.CharField(max_length=200)),
                ('State_id', models.CharField(max_length=200)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('moonrise', models.TimeField()),
                ('moonset', models.TimeField()),
                ('tithi', models.CharField(max_length=200)),
                ('vikram_samvat', models.CharField(max_length=200)),
                ('samvat_shaka', models.CharField(max_length=200)),
                ('nakshatra', models.CharField(max_length=200)),
                ('yog', models.CharField(max_length=200)),
                ('karan', models.CharField(max_length=200)),
                ('City_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.citymaster')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.monthmaster')),
            ],
        ),
        migrations.CreateModel(
            name='moon_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('birth_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.citymaster')),
            ],
        ),
        migrations.CreateModel(
            name='male_Horoscope_Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=200)),
                ('m_DOB', models.DateField()),
                ('m_time_of_birth', models.TimeField()),
                ('m_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.citymaster')),
            ],
        ),
        migrations.CreateModel(
            name='kundli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundli_name', models.CharField(max_length=200)),
                ('kundli_DOB', models.DateField()),
                ('kundli_time_of_birth', models.TimeField()),
                ('kundli_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.citymaster')),
            ],
        ),
        migrations.CreateModel(
            name='female_Horoscope_Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('f_DOB', models.DateField()),
                ('f_time_of_birth', models.TimeField()),
                ('f_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.citymaster')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horoscope_date', models.DateField()),
                ('horoscope_title', models.CharField(max_length=200)),
                ('horoscope_description', models.TextField()),
                ('sign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.sign')),
            ],
        ),
        migrations.CreateModel(
            name='clientsignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Country_id', models.CharField(max_length=500)),
                ('State_id', models.CharField(max_length=500)),
                ('Address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
                ('IsActive', models.IntegerField()),
                ('IsDeleted', models.IntegerField()),
                ('createby', models.CharField(max_length=30)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=30)),
                ('ModifiedDate', models.DateField()),
                ('is_admin', models.IntegerField()),
                ('City_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.citymaster')),
            ],
        ),
        
        
    ]
