# Generated by Django 4.1.6 on 2023-03-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astroakshat', '0003_astro_admin_isdeleted_daily_articals_isdeleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astro_admin',
            name='astropassword',
        ),
    ]
