# Generated by Django 4.1.6 on 2023-04-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astroakshat', '0004_remove_astro_admin_astropassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_pooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=500)),
                ('c_Email', models.EmailField(max_length=254)),
                ('c_phoneno', models.IntegerField()),
                ('preferred_time', models.TimeField()),
                ('preferred_date', models.DateField()),
                ('reason_for_appoint', models.CharField(max_length=1000000)),
                ('book_request', models.IntegerField()),
                ('pooja_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.astro_pooja')),
            ],
        ),
        migrations.CreateModel(
            name='astro_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=500)),
                ('c_Email', models.EmailField(max_length=254)),
                ('c_phoneno', models.IntegerField()),
                ('preferred_time', models.TimeField()),
                ('preferred_date', models.DateField()),
                ('reason_for_appoint', models.CharField(max_length=1000000)),
                ('appoint_status', models.IntegerField()),
                ('astroname_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.astro_admin')),
            ],
        ),
    ]
