# Generated by Django 4.1.6 on 2023-04-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astroakshat', '0005_book_pooja_astro_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundli',
            name='clientlog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moon_sign',
            name='IsDeleted',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moon_sign',
            name='clientlog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='create_moonsign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('IsDeleted', models.IntegerField()),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
                ('moon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.moon_sign')),
            ],
        ),
        migrations.CreateModel(
            name='create_kundli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('IsDeleted', models.IntegerField()),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
                ('kundli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.kundli')),
            ],
        ),
    ]
