# Generated by Django 4.1.6 on 2023-04-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroakshat', '0006_kundli_clientlog_moon_sign_isdeleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundli',
            name='IsRequest',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moon_sign',
            name='IsRequest',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
