# Generated by Django 4.1.6 on 2023-04-19 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astroakshat', '0007_kundli_isrequest_moon_sign_isrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astro_appointment',
            name='astroname_id',
        ),
        migrations.AddField(
            model_name='astro_appointment',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup'),
            preserve_default=False,
        ),
    ]
