# Generated by Django 4.1.6 on 2023-05-04 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astroakshat', '0008_remove_astro_appointment_astroname_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_pooja',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup'),
            preserve_default=False,
        ),
    ]
