# Generated by Django 4.1.6 on 2023-05-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astroakshat', '0009_book_pooja_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='vastu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('IsDeleted', models.IntegerField()),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='tarrot_reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('IsDeleted', models.IntegerField()),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='plam_reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('IsDeleted', models.IntegerField()),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='match_matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('IsRequest', models.IntegerField()),
                ('IsDeleted', models.IntegerField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.citymaster')),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='manglik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('IsRequest', models.IntegerField()),
                ('IsDeleted', models.IntegerField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.citymaster')),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='lalkitab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('IsDeleted', models.IntegerField()),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='kundli_dosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('IsRequest', models.IntegerField()),
                ('IsDeleted', models.IntegerField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.citymaster')),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='create_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('IsDeleted', models.IntegerField()),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='create_manglik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('IsDeleted', models.IntegerField()),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='create_kundli_dosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('IsDeleted', models.IntegerField()),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='create_birth_journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('IsDeleted', models.IntegerField()),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
        migrations.CreateModel(
            name='birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('IsRequest', models.IntegerField()),
                ('IsDeleted', models.IntegerField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.citymaster')),
                ('clientlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astroakshat.clientsignup')),
            ],
        ),
    ]
