# Generated by Django 4.1.6 on 2023-08-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astroakshat', '0010_vastu_tarrot_reading_plam_reading_match_matching_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lalkitab',
            name='clientlog',
        ),
        migrations.RemoveField(
            model_name='plam_reading',
            name='clientlog',
        ),
        migrations.RemoveField(
            model_name='tarrot_reading',
            name='clientlog',
        ),
        migrations.RemoveField(
            model_name='vastu',
            name='clientlog',
        ),
    ]
